---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: multiplayersample
    release: r1
  name: multiplayersample
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 0
  selector:
    matchLabels:
      app: multiplayersample
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multiplayersample
    spec:
      serviceAccountName: gs-terminator
      containers:
      - name: multiplayersample
        image: 356566070122.dkr.ecr.us-west-2.amazonaws.com/multiplayersample-build:7
        imagePullPolicy: Always
        command: ["/start.py"]
        env:
          - name: CONSOLE_ADDR
            value: "35.155.192.206"
          - name: AWS_DEFAULT_REGION
            valueFrom:
              configMapKeyRef:
                name: region-config
                key: aws.default.region
          - name: GROUP
            value: "multiplayersample"
          - name: QUEUENAME
            valueFrom:
              configMapKeyRef:
                name: region-config
                key: game.server.queue.name
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      hostNetwork: true
